[package]
name = "day-20"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.22.3"
building-blocks = "0.7.1"
nalgebra = "0.29.0"
