[package]
name = "day-7"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
proptest = "1.0.0"
criterion = "0.3.5"

[[bench]]
name = "bench"
harness = false

[dependencies]
rand = "0.8.4"
